name: "Deploy to VPS"
on:
  workflow_dispatch:
jobs:
  deploy:
    name: deploy to remote vps
    runs-on: host
    permissions:
      contents: write
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /root/nodeChat
            git pull
            npm ci
            pm2 restart node-chat
